# Project information
site_name: Onlinebijbelverklaring.nl
site_url: https://onlinebijbelverklaring.nl
site_author: Onlinebijbelverklaring.nl
site_description: >-
  De volledige bijbelverklaringen van Matthew Henry en Karl August Dachsel online

# Copyright
copyright: |
  Content van deze website is vrij van auteursrecht en is daardoor vrij te gebruiken en/of publiceren.
  
# Repository
repo_url: https://github.com/onlinebijbelverklaring
edit_uri: blob/main/docs/
repo_name: onlinebijbelverklaring.github.io

# Configuration
theme:
  font:
    text: Montserrat
  icon:
    repo: fontawesome/brands/github
    edit: material/playlist-edit
    view: material/playlist-edit
    logo: material/book-open-variant
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.path 
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.expand
#    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    # - search.suggest
    # - search.highligt
    # - search.share
    - content.tabs.link
    - content.code.annotatioin
    - content.code.copy
    - content.tooltips
    # - content.action.edit
    # - content.footnote.tooltips
    # - content.code.select
  language: nl
  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Donkere modus
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Lichte modus

# Additional configuration
extra:
   analytics:
    provider: google
    property: G-VQEZZ3SCH3

# Markdown Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.caret
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true



plugins:
  - search:
      enabled: false



# Navigation menu
nav:
  - Welkom:
    - Welkom: index.md
    - Bijbel indeling: bijbelindeling.md
    - Voortgang: voortgang.md
  - Matthew Henry:
    - Oude Testament:
      - Genesis:
        - Genesis: matthewhenry/Genesis/index.md
        - Genesis 1: matthewhenry/Genesis/Genesis1/index.md
        - Genesis 2: matthewhenry/Genesis/Genesis2/index.md
        - Genesis 3: matthewhenry/Genesis/Genesis3/index.md
        - Genesis 4: matthewhenry/Genesis/Genesis4index.md
        - Genesis 5: matthewhenry/Genesis/Genesis5/index.md
        - Genesis 6: matthewhenry/Genesis/Genesis6/index.md
        - Genesis 7: matthewhenry/Genesis/Genesis7/index.md
        - Genesis 8: matthewhenry/Genesis/Genesis8/index.md
        - Genesis 9: matthewhenry/Genesis/Genesis9/index.md
        - Genesis 10: matthewhenry/Genesis/Genesis10/index.md
        - Genesis 11: matthewhenry/Genesis/Genesis11/index.md
        - Genesis 12: matthewhenry/Genesis/Genesis12/index.md
        - Genesis 13: matthewhenry/Genesis/Genesis13/index.md
        - Genesis 14: matthewhenry/Genesis/Genesis14/index.md
        - Genesis 15: matthewhenry/Genesis/Genesis15/index.md
        - Genesis 16: matthewhenry/Genesis/Genesis16/index.md
        - Genesis 17: matthewhenry/Genesis/Genesis17/index.md
        - Genesis 18: matthewhenry/Genesis/Genesis18/index.md
        - Genesis 19: matthewhenry/Genesis/Genesis19/index.md
        - Genesis 20: Genesis/Genesis20/index.md
        - Genesis 21: Genesis/Genesis21/index.md
        - Genesis 22: Genesis/Genesis22/index.md
        - Genesis 23: Genesis/Genesis23/index.md
        - Genesis 24: Genesis/Genesis24/index.md
        - Genesis 25: Genesis/Genesis25/index.md
        - Genesis 26: Genesis/Genesis26/index.md
        - Genesis 27: Genesis/Genesis27/index.md
        - Genesis 28: Genesis/Genesis28/index.md
        - Genesis 29: Genesis/Genesis29/index.md
        - Genesis 30: Genesis/Genesis30/index.md
        - Genesis 31: Genesis/Genesis31/index.md
        - Genesis 32: Genesis/Genesis32/index.md
        - Genesis 33: Genesis/Genesis33/index.md
        - Genesis 34: Genesis/Genesis34/index.md
        - Genesis 35: Genesis/Genesis35/index.md
        - Genesis 36: Genesis/Genesis36/index.md
        - Genesis 37: Genesis/Genesis37/index.md
        - Genesis 38: Genesis/Genesis38/index.md
        - Genesis 39: Genesis/Genesis39/index.md
        - Genesis 40: Genesis/Genesis40/index.md
        - Genesis 41: Genesis/Genesis41/index.md
        - Genesis 42: Genesis/Genesis42/index.md
        - Genesis 43: Genesis/Genesis43/index.md
        - Genesis 44: Genesis/Genesis44/index.md
        - Genesis 45: Genesis/Genesis45/index.md
        - Genesis 46: Genesis/Genesis46/index.md
        - Genesis 47: Genesis/Genesis47/index.md
        - Genesis 48: Genesis/Genesis48/index.md
        - Genesis 49: Genesis/Genesis49/index.md
        - Genesis 50: Genesis/Genesis50/index.md
      - Éxodus:
        - Éxodus: Exodus/index.md
        - Éxodus 1: Exodus/Exodus1/index.md
        - Éxodus 2: Exodus/Exodus2/index.md
        - Éxodus 3: Exodus/Exodus3/index.md
        - Éxodus 4: Exodus/Exodus4/index.md
        - Éxodus 5: Exodus/Exodus5/index.md
        - Éxodus 6: Exodus/Exodus6/index.md
        - Éxodus 7: Exodus/Exodus7/index.md
        - Éxodus 8: Exodus/Exodus8/index.md
        - Éxodus 9: Exodus/Exodus9/index.md
        - Éxodus 10: Exodus/Exodus10/index.md
        - Éxodus 11: Exodus/Exodus11/index.md
        - Éxodus 12: Exodus/Exodus12/index.md
        - Éxodus 13: Exodus/Exodus13/index.md
        - Éxodus 14: Exodus/Exodus14/index.md
        - Éxodus 15: Exodus/Exodus15/index.md
        - Éxodus 16: Exodus/Exodus16/index.md
        - Éxodus 17: Exodus/Exodus17/index.md
        - Éxodus 18: Exodus/Exodus18/index.md
        - Éxodus 19: Exodus/Exodus19/index.md
        - Éxodus 20: Exodus/Exodus20/index.md
        - Éxodus 21: Exodus/Exodus21/index.md
        - Éxodus 22: Exodus/Exodus22/index.md
        - Éxodus 23: Exodus/Exodus23/index.md
        - Éxodus 24: Exodus/Exodus24/index.md
        - Éxodus 25: Exodus/Exodus25/index.md
        - Éxodus 26: Exodus/Exodus26/index.md
        - Éxodus 27: Exodus/Exodus27/index.md
        - Éxodus 28: Exodus/Exodus28/index.md
        - Éxodus 29: Exodus/Exodus29/index.md
        - Éxodus 30: Exodus/Exodus30/index.md
        - Éxodus 31: Exodus/Exodus31/index.md
        - Éxodus 32: Exodus/Exodus32/index.md
        - Éxodus 33: Exodus/Exodus33/index.md
        - Éxodus 34: Exodus/Exodus34/index.md
        - Éxodus 35: Exodus/Exodus35/index.md
        - Éxodus 36: Exodus/Exodus36/index.md
        - Éxodus 37: Exodus/Exodus37/index.md
        - Éxodus 38: Exodus/Exodus38/index.md
        - Éxodus 39: Exodus/Exodus39/index.md
        - Éxodus 40: Exodus/Exodus40/index.md
    - Nieuwe Testament:
      - tutorials/index.md
      - Genesis:
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - Exodus:
        - tutorials/social/basic.md
        - tutorials/social/custom.md
