# Project information
site_name: Onlinebijbelverklaring.nl
site_url: https://onlinebijbelverklaring.nl
site_author: Onlinebijbelverklaring.nl
site_description: >-
  De volledige bijbelverklaringen van Matthew Henry en Karl August Dachsel online

# Copyright
copyright: |
  Content van deze website is vrij van auteursrecht en is daardoor vrij te gebruiken en/of publiceren.
  
# Repository
repo_url: https://github.com/onlinebijbelverklaring
edit_uri: blob/main/docs/
repo_name: onlinebijbelverklaring.github.io

# Configuration
theme:
  font:
    text: Montserrat
  icon:
    repo: fontawesome/brands/github
    edit: material/playlist-edit
    view: material/playlist-edit
    logo: material/book-open-variant
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.path 
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.expand
#    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    # - search.suggest
    # - search.highligt
    # - search.share
    - content.tabs.link
    - content.code.annotatioin
    - content.code.copy
    - content.tooltips
    # - content.action.edit
    # - content.footnote.tooltips
    # - content.code.select
  language: nl
  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Donkere modus
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Lichte modus

# Additional configuration
extra:
   analytics:
    provider: google
    property: G-VQEZZ3SCH3

# Markdown Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.caret
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true



plugins:
  - search:
      enabled: false



# Navigation menu
nav:
  - Welkom:
    - Welkom: index.md
    - Bijbel indeling: bijbelindeling.md
    - Voortgang: voortgang.md
  - Matthew Henry:
    - Oude Testament:
      - Genesis:
        - Genesis: matthewhenry/Genesis/index.md
        - Genesis 1: matthewhenry/Genesis/Genesis1/index.md
        - Genesis 2: matthewhenry/Genesis/Genesis2/index.md
        - Genesis 3: matthewhenry/Genesis/Genesis3/index.md
        - Genesis 4: matthewhenry/Genesis/Genesis4index.md
        - Genesis 5: matthewhenry/Genesis/Genesis5/index.md
        - Genesis 6: matthewhenry/Genesis/Genesis6/index.md
        - Genesis 7: matthewhenry/Genesis/Genesis7/index.md
        - Genesis 8: matthewhenry/Genesis/Genesis8/index.md
        - Genesis 9: matthewhenry/Genesis/Genesis9/index.md
        - Genesis 10: matthewhenry/Genesis/Genesis10/index.md
        - Genesis 11: matthewhenry/Genesis/Genesis11/index.md
        - Genesis 12: matthewhenry/Genesis/Genesis12/index.md
        - Genesis 13: matthewhenry/Genesis/Genesis13/index.md
        - Genesis 14: matthewhenry/Genesis/Genesis14/index.md
        - Genesis 15: matthewhenry/Genesis/Genesis15/index.md
        - Genesis 16: matthewhenry/Genesis/Genesis16/index.md
        - Genesis 17: matthewhenry/Genesis/Genesis17/index.md
        - Genesis 18: matthewhenry/Genesis/Genesis18/index.md
        - Genesis 19: matthewhenry/Genesis/Genesis19/index.md
      - Exodus:
        - tutorials/social/basic.md
        - tutorials/social/custom.md
    - Nieuwe Testament:
      - tutorials/index.md
      - Genesis:
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - Exodus:
        - tutorials/social/basic.md
        - tutorials/social/custom.md
