# Project information
site_name: Onlinebijbelverklaring.nl
site_url: https://onlinebijbelverklaring.nl
site_author: Onlinebijbelverklaring.nl
site_description: >-
  De volledige bijbelverklaringen van Matthew Henry en Karl August Dachsel online

# Copyright
copyright: |
  Content van deze website is vrij van auteursrecht en is daardoor vrij te gebruiken en/of publiceren.
  
# Repository
repo_url: https://github.com/onlinebijbelverklaring
edit_uri: blob/main/docs/
repo_name: onlinebijbelverklaring.github.io

# Configuration
theme:
  font:
    text: Montserrat
  icon:
    repo: fontawesome/brands/github
    edit: material/playlist-edit
    view: material/playlist-edit
    logo: material/book-open-variant
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.path 
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.expand
#    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    # - search.suggest
    # - search.highligt
    # - search.share
    - content.tabs.link
    - content.code.annotatioin
    - content.code.copy
    - content.tooltips
    # - content.action.edit
    # - content.footnote.tooltips
    # - content.code.select
  language: nl
  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Donkere modus
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Lichte modus

# Additional configuration
extra:
   analytics:
    provider: google
    property: G-VQEZZ3SCH3

# Markdown Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.caret
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true



plugins:
  - search:
      enabled: false



# Navigation menu
nav:
  - Welkom:
    - Welkom: index.md
    - Bijbel indeling: bijbelindeling.md
    - Voortgang: voortgang.md
  - Matthew Henry:
    - Inleiding: matthewhenry/index.md
    - Levensschets: matthewhenry/levensschets.md
    - Voorrede: matthewhenry/voorrede.md
    - Oude Testament:
      - Genesis:
        - Genesis: matthewhenry/Genesis/index.md
        - Genesis 1: matthewhenry/Genesis/Genesis1/index.md
        - Genesis 2: matthewhenry/Genesis/Genesis2/index.md
        - Genesis 3: matthewhenry/Genesis/Genesis3/index.md
        - Genesis 4: matthewhenry/Genesis/Genesis4index.md
        - Genesis 5: matthewhenry/Genesis/Genesis5/index.md
        - Genesis 6: matthewhenry/Genesis/Genesis6/index.md
        - Genesis 7: matthewhenry/Genesis/Genesis7/index.md
        - Genesis 8: matthewhenry/Genesis/Genesis8/index.md
        - Genesis 9: matthewhenry/Genesis/Genesis9/index.md
        - Genesis 10: matthewhenry/Genesis/Genesis10/index.md
        - Genesis 11: matthewhenry/Genesis/Genesis11/index.md
        - Genesis 12: matthewhenry/Genesis/Genesis12/index.md
        - Genesis 13: matthewhenry/Genesis/Genesis13/index.md
        - Genesis 14: matthewhenry/Genesis/Genesis14/index.md
        - Genesis 15: matthewhenry/Genesis/Genesis15/index.md
        - Genesis 16: matthewhenry/Genesis/Genesis16/index.md
        - Genesis 17: matthewhenry/Genesis/Genesis17/index.md
        - Genesis 18: matthewhenry/Genesis/Genesis18/index.md
        - Genesis 19: matthewhenry/Genesis/Genesis19/index.md
        - Genesis 20: matthewhenry/Genesis/Genesis20/index.md
        - Genesis 21: matthewhenry/Genesis/Genesis21/index.md
        - Genesis 22: matthewhenry/Genesis/Genesis22/index.md
        - Genesis 23: matthewhenry/Genesis/Genesis23/index.md
        - Genesis 24: matthewhenry/Genesis/Genesis24/index.md
        - Genesis 25: matthewhenry/Genesis/Genesis25/index.md
        - Genesis 26: matthewhenry/Genesis/Genesis26/index.md
        - Genesis 27: matthewhenry/Genesis/Genesis27/index.md
        - Genesis 28: matthewhenry/Genesis/Genesis28/index.md
        - Genesis 29: matthewhenry/Genesis/Genesis29/index.md
        - Genesis 30: matthewhenry/Genesis/Genesis30/index.md
        - Genesis 31: matthewhenry/Genesis/Genesis31/index.md
        - Genesis 32: matthewhenry/Genesis/Genesis32/index.md
        - Genesis 33: matthewhenry/Genesis/Genesis33/index.md
        - Genesis 34: matthewhenry/Genesis/Genesis34/index.md
        - Genesis 35: matthewhenry/Genesis/Genesis35/index.md
        - Genesis 36: matthewhenry/Genesis/Genesis36/index.md
        - Genesis 37: matthewhenry/Genesis/Genesis37/index.md
        - Genesis 38: matthewhenry/Genesis/Genesis38/index.md
        - Genesis 39: matthewhenry/Genesis/Genesis39/index.md
        - Genesis 40: matthewhenry/Genesis/Genesis40/index.md
        - Genesis 41: matthewhenry/Genesis/Genesis41/index.md
        - Genesis 42: matthewhenry/Genesis/Genesis42/index.md
        - Genesis 43: matthewhenry/Genesis/Genesis43/index.md
        - Genesis 44: matthewhenry/Genesis/Genesis44/index.md
        - Genesis 45: matthewhenry/Genesis/Genesis45/index.md
        - Genesis 46: matthewhenry/Genesis/Genesis46/index.md
        - Genesis 47: matthewhenry/Genesis/Genesis47/index.md
        - Genesis 48: matthewhenry/Genesis/Genesis48/index.md
        - Genesis 49: matthewhenry/Genesis/Genesis49/index.md
        - Genesis 50: matthewhenry/Genesis/Genesis50/index.md
      - Éxodus:
        - Éxodus: matthewhenry/Exodus/index.md
        - Éxodus 1: matthewhenry/Exodus/Exodus1/index.md
        - Éxodus 2: matthewhenry/Exodus/Exodus2/index.md
        - Éxodus 3: matthewhenry/Exodus/Exodus3/index.md
        - Éxodus 4: matthewhenry/Exodus/Exodus4/index.md
        - Éxodus 5: matthewhenry/Exodus/Exodus5/index.md
        - Éxodus 6: matthewhenry/Exodus/Exodus6/index.md
        - Éxodus 7: matthewhenry/Exodus/Exodus7/index.md
        - Éxodus 8: matthewhenry/Exodus/Exodus8/index.md
        - Éxodus 9: matthewhenry/Exodus/Exodus9/index.md
        - Éxodus 10: matthewhenry/Exodus/Exodus10/index.md
        - Éxodus 11: matthewhenry/Exodus/Exodus11/index.md
        - Éxodus 12: matthewhenry/Exodus/Exodus12/index.md
        - Éxodus 13: matthewhenry/Exodus/Exodus13/index.md
        - Éxodus 14: matthewhenry/Exodus/Exodus14/index.md
        - Éxodus 15: matthewhenry/Exodus/Exodus15/index.md
        - Éxodus 16: matthewhenry/Exodus/Exodus16/index.md
        - Éxodus 17: matthewhenry/Exodus/Exodus17/index.md
        - Éxodus 18: matthewhenry/Exodus/Exodus18/index.md
        - Éxodus 19: matthewhenry/Exodus/Exodus19/index.md
        - Éxodus 20: matthewhenry/Exodus/Exodus20/index.md
        - Éxodus 21: matthewhenry/Exodus/Exodus21/index.md
        - Éxodus 22: matthewhenry/Exodus/Exodus22/index.md
        - Éxodus 23: matthewhenry/Exodus/Exodus23/index.md
        - Éxodus 24: matthewhenry/Exodus/Exodus24/index.md
        - Éxodus 25: matthewhenry/Exodus/Exodus25/index.md
        - Éxodus 26: matthewhenry/Exodus/Exodus26/index.md
        - Éxodus 27: matthewhenry/Exodus/Exodus27/index.md
        - Éxodus 28: matthewhenry/Exodus/Exodus28/index.md
        - Éxodus 29: matthewhenry/Exodus/Exodus29/index.md
        - Éxodus 30: matthewhenry/Exodus/Exodus30/index.md
        - Éxodus 31: matthewhenry/Exodus/Exodus31/index.md
        - Éxodus 32: matthewhenry/Exodus/Exodus32/index.md
        - Éxodus 33: matthewhenry/Exodus/Exodus33/index.md
        - Éxodus 34: matthewhenry/Exodus/Exodus34/index.md
        - Éxodus 35: matthewhenry/Exodus/Exodus35/index.md
        - Éxodus 36: matthewhenry/Exodus/Exodus36/index.md
        - Éxodus 37: matthewhenry/Exodus/Exodus37/index.md
        - Éxodus 38: matthewhenry/Exodus/Exodus38/index.md
        - Éxodus 39: matthewhenry/Exodus/Exodus39/index.md
        - Éxodus 40: matthewhenry/Exodus/Exodus40/index.md
      - Leviticus: 
        - Leviticus: matthewhenry/Leviticus/index.md
        - Leviticus 1: matthewhenry/Leviticus/Leviticus1/index.md
        - Leviticus 2: matthewhenry/Leviticus/Leviticus2/index.md
        - Leviticus 3: matthewhenry/Leviticus/Leviticus3/index.md
        - Leviticus 4: matthewhenry/Leviticus/Leviticus4/index.md
        - Leviticus 5: matthewhenry/Leviticus/Leviticus5/index.md
        - Leviticus 6: matthewhenry/Leviticus/Leviticus6/index.md
        - Leviticus 7: matthewhenry/Leviticus/Leviticus7/index.md
        - Leviticus 8: matthewhenry/Leviticus/Leviticus8/index.md
        - Leviticus 9: matthewhenry/Leviticus/Leviticus9/index.md
        - Leviticus 10: matthewhenry/Leviticus/Leviticus10/index.md
        - Leviticus 11: matthewhenry/Leviticus/Leviticus11/index.md
        - Leviticus 12: matthewhenry/Leviticus/Leviticus12/index.md
        - Leviticus 13: matthewhenry/Leviticus/Leviticus13/index.md
        - Leviticus 14: matthewhenry/Leviticus/Leviticus14/index.md
        - Leviticus 15: matthewhenry/Leviticus/Leviticus15/index.md
        - Leviticus 16: matthewhenry/Leviticus/Leviticus16/index.md
        - Leviticus 17: matthewhenry/Leviticus/Leviticus17/index.md
        - Leviticus 18: matthewhenry/Leviticus/Leviticus18/index.md
        - Leviticus 19: matthewhenry/Leviticus/Leviticus19/index.md
        - Leviticus 20: matthewhenry/Leviticus/Leviticus20/index.md
        - Leviticus 21: matthewhenry/Leviticus/Leviticus21/index.md
        - Leviticus 22: matthewhenry/Leviticus/Leviticus22/index.md
        - Leviticus 23: matthewhenry/Leviticus/Leviticus23/index.md
        - Leviticus 24: matthewhenry/Leviticus/Leviticus24/index.md
        - Leviticus 25: matthewhenry/Leviticus/Leviticus25/index.md
        - Leviticus 26: matthewhenry/Leviticus/Leviticus26/index.md
        - Leviticus 27: matthewhenry/Leviticus/Leviticus27/index.md
      - Numeri: 
        - Numeri: matthewhenry/Numeri/index.md
        - Numeri 1: matthewhenry/Numeri/Numeri1/index.md
        - Numeri 2: matthewhenry/Numeri/Numeri2/index.md
        - Numeri 3: matthewhenry/Numeri/Numeri3/index.md
        - Numeri 4: matthewhenry/Numeri/Numeri4/index.md
        - Numeri 5: matthewhenry/Numeri/Numeri5/index.md
        - Numeri 6: matthewhenry/Numeri/Numeri6/index.md
        - Numeri 7: matthewhenry/Numeri/Numeri7/index.md
        - Numeri 8: matthewhenry/Numeri/Numeri8/index.md
        - Numeri 9: matthewhenry/Numeri/Numeri9/index.md
        - Numeri 10: matthewhenry/Numeri/Numeri10/index.md
        - Numeri 11: matthewhenry/Numeri/Numeri11/index.md
        - Numeri 12: matthewhenry/Numeri/Numeri12/index.md
        - Numeri 13: matthewhenry/Numeri/Numeri13/index.md
        - Numeri 14: matthewhenry/Numeri/Numeri14/index.md
        - Numeri 15: matthewhenry/Numeri/Numeri15/index.md
        - Numeri 16: matthewhenry/Numeri/Numeri16/index.md
        - Numeri 17: matthewhenry/Numeri/Numeri17/index.md
        - Numeri 18: matthewhenry/Numeri/Numeri18/index.md
        - Numeri 19: matthewhenry/Numeri/Numeri19/index.md
        - Numeri 20: matthewhenry/Numeri/Numeri20/index.md
        - Numeri 21: matthewhenry/Numeri/Numeri21/index.md
        - Numeri 22: matthewhenry/Numeri/Numeri22/index.md
        - Numeri 23: matthewhenry/Numeri/Numeri23/index.md
        - Numeri 24: matthewhenry/Numeri/Numeri24/index.md
        - Numeri 25: matthewhenry/Numeri/Numeri25/index.md
        - Numeri 26: matthewhenry/Numeri/Numeri26/index.md
        - Numeri 27: matthewhenry/Numeri/Numeri27/index.md
        - Numeri 28: matthewhenry/Numeri/Numeri28/index.md
        - Numeri 29: matthewhenry/Numeri/Numeri29/index.md
        - Numeri 30: matthewhenry/Numeri/Numeri30/index.md
        - Numeri 31: matthewhenry/Numeri/Numeri31/index.md
        - Numeri 32: matthewhenry/Numeri/Numeri32/index.md
        - Numeri 33: matthewhenry/Numeri/Numeri33/index.md
        - Numeri 34: matthewhenry/Numeri/Numeri34/index.md
        - Numeri 35: matthewhenry/Numeri/Numeri35/index.md
        - Numeri 36: matthewhenry/Numeri/Numeri36/index.md
      - Deuteronomium: 
        - Deuteronomium: matthewhenry/Deuteronomium/index.md
        - Deuteronomium 1: matthewhenry/Deuteronomium/Deuteronomium1/index.md
        - Deuteronomium 2: matthewhenry/Deuteronomium/Deuteronomium2/index.md
        - Deuteronomium 3: matthewhenry/Deuteronomium/Deuteronomium3/index.md
        - Deuteronomium 4: matthewhenry/Deuteronomium/Deuteronomium4/index.md
        - Deuteronomium 5: matthewhenry/Deuteronomium/Deuteronomium5/index.md
        - Deuteronomium 6: matthewhenry/Deuteronomium/Deuteronomium6/index.md
        - Deuteronomium 7: matthewhenry/Deuteronomium/Deuteronomium7/index.md
        - Deuteronomium 8: matthewhenry/Deuteronomium/Deuteronomium8/index.md
        - Deuteronomium 9: matthewhenry/Deuteronomium/Deuteronomium9/index.md
        - Deuteronomium 10: matthewhenry/Deuteronomium/Deuteronomium10/index.md
        - Deuteronomium 11: matthewhenry/Deuteronomium/Deuteronomium11/index.md
        - Deuteronomium 12: matthewhenry/Deuteronomium/Deuteronomium12/index.md
        - Deuteronomium 13: matthewhenry/Deuteronomium/Deuteronomium13/index.md
        - Deuteronomium 14: matthewhenry/Deuteronomium/Deuteronomium14/index.md
        - Deuteronomium 15: matthewhenry/Deuteronomium/Deuteronomium15/index.md
        - Deuteronomium 16: matthewhenry/Deuteronomium/Deuteronomium16/index.md
        - Deuteronomium 17: matthewhenry/Deuteronomium/Deuteronomium17/index.md
        - Deuteronomium 18: matthewhenry/Deuteronomium/Deuteronomium18/index.md
        - Deuteronomium 19: matthewhenry/Deuteronomium/Deuteronomium19/index.md
        - Deuteronomium 20: matthewhenry/Deuteronomium/Deuteronomium20/index.md
        - Deuteronomium 21: matthewhenry/Deuteronomium/Deuteronomium21/index.md
        - Deuteronomium 22: matthewhenry/Deuteronomium/Deuteronomium22/index.md
        - Deuteronomium 23: matthewhenry/Deuteronomium/Deuteronomium23/index.md
        - Deuteronomium 24: matthewhenry/Deuteronomium/Deuteronomium24/index.md
        - Deuteronomium 25: matthewhenry/Deuteronomium/Deuteronomium25/index.md
        - Deuteronomium 26: matthewhenry/Deuteronomium/Deuteronomium26/index.md
        - Deuteronomium 27: matthewhenry/Deuteronomium/Deuteronomium27/index.md
        - Deuteronomium 28: matthewhenry/Deuteronomium/Deuteronomium28/index.md
        - Deuteronomium 29: matthewhenry/Deuteronomium/Deuteronomium29/index.md
        - Deuteronomium 30: matthewhenry/Deuteronomium/Deuteronomium30/index.md
        - Deuteronomium 31: matthewhenry/Deuteronomium/Deuteronomium31/index.md
        - Deuteronomium 32: matthewhenry/Deuteronomium/Deuteronomium32/index.md
        - Deuteronomium 33: matthewhenry/Deuteronomium/Deuteronomium33/index.md
        - Deuteronomium 34: matthewhenry/Deuteronomium/Deuteronomium34/index.md
    - Nieuwe Testament:
      - Genesis:
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - Exodus:
        - tutorials/social/basic.md
        - tutorials/social/custom.md
